name: game_mobile
description: "Color Prediction Blockchain Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Web3 & Wallet
  walletconnect_flutter_v2: ^2.1.15
  web3dart: ^2.7.3
  http: ^1.2.0
  
  # Backend
  supabase_flutter: ^2.5.0
  
  # State Management
  provider: ^6.1.2
  
  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # Utils
  url_launcher: ^6.2.5
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
